# Generated by Django 4.2 on 2024-03-13 17:15

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=128, verbose_name="название категории"
                    ),
                ),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="условие вопроса")),
                (
                    "weight",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "json_body",
                    models.JSONField(
                        help_text="информация о типе вопроса и правильном ответе по определенной структуре",
                        verbose_name="техническая характеристика вопроса",
                    ),
                ),
            ],
            options={
                "verbose_name": "вопрос",
                "verbose_name_plural": "вопросы",
            },
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="название теста",
                        max_length=128,
                        verbose_name="название теста",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="краткая информация о тесте (опционально)",
                        verbose_name="описание теста",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="аватарка теста",
                        null=True,
                        upload_to="user_tests/%Y/%m/%d/",
                        verbose_name="аватар",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="время создания теста",
                        verbose_name="время создания теста",
                    ),
                ),
                (
                    "deadline_open",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024,
                            3,
                            13,
                            17,
                            15,
                            41,
                            229891,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                (
                    "deadline_close",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="создатель теста",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="автор теста",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="категория этого теста (может быть только одна!)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category",
                        to="user_tests.category",
                        verbose_name="категория",
                    ),
                ),
                (
                    "questions",
                    models.ManyToManyField(
                        help_text="список вопросов в этом тесте",
                        to="user_tests.question",
                        verbose_name="вопросы",
                    ),
                ),
            ],
            options={
                "verbose_name": "тест",
                "verbose_name_plural": "тесты",
            },
        ),
        migrations.CreateModel(
            name="QuestionAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer",
                    models.CharField(
                        blank=True,
                        help_text="ответ, данный пользователем",
                        max_length=64,
                        null=True,
                        verbose_name="ответ",
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        help_text="меняет значение в зависимости от правильности введенных данных",
                        verbose_name="правильность ответа",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_tests.question",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ответ",
                "verbose_name_plural": "ответы",
            },
        ),
    ]
