# Generated by Django 4.2 on 2024-03-14 16:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "user_tests",
            "0002_remove_test_avatar_alter_question_weight_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="avatar",
            name="test",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image",
                to="user_tests.test",
                verbose_name="тест",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="deadline_open",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024,
                    3,
                    14,
                    16,
                    18,
                    3,
                    369441,
                    tzinfo=datetime.timezone.utc,
                )
            ),
        ),
    ]
