# Generated by Django 4.2 on 2024-03-14 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_tests", "0003_alter_avatar_test_alter_test_deadline_open"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avatar",
            name="image",
            field=models.ImageField(
                upload_to="images/%Y/%m/%d/", verbose_name="изображение"
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="deadline_open",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024,
                    3,
                    14,
                    16,
                    35,
                    22,
                    617621,
                    tzinfo=datetime.timezone.utc,
                )
            ),
        ),
    ]
