# Generated by Django 4.2 on 2024-03-14 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "user_tests",
            "0002_remove_test_avatar_alter_question_weight_and_more_squashed_0004_alter_avatar_image_alter_test_deadline_open",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="deadline_open",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024,
                    3,
                    14,
                    16,
                    36,
                    50,
                    548267,
                    tzinfo=datetime.timezone.utc,
                )
            ),
        ),
    ]
