# Generated by Django 4.2 on 2024-03-14 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_tests", "0006_alter_test_deadline_open_questionimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="deadline_open",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 14, 17, 19, 5, 3474, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
