# Generated by Django 4.2 on 2024-03-27 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_tests", "0007_alter_test_deadline_open"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="deadline_open",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024,
                    3,
                    27,
                    19,
                    31,
                    45,
                    787826,
                    tzinfo=datetime.timezone.utc,
                )
            ),
        ),
    ]
