# Generated by Django 4.2 on 2024-03-28 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_tests", "0008_alter_test_deadline_open"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="deadline_open",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024,
                    3,
                    28,
                    8,
                    40,
                    50,
                    359995,
                    tzinfo=datetime.timezone.utc,
                )
            ),
        ),
    ]
