# Generated by Django 4.2 on 2024-03-28 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_tests", "0010_alter_test_deadline_open"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Avatar",
            new_name="TestAvatar",
        ),
        migrations.AlterField(
            model_name="test",
            name="deadline_open",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024,
                    3,
                    28,
                    15,
                    16,
                    13,
                    288455,
                    tzinfo=datetime.timezone.utc,
                )
            ),
        ),
    ]
