# Generated by Django 4.2 on 2024-03-28 16:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        (
            "user_tests",
            "0011_rename_avatar_testavatar_alter_test_deadline_open",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="deadline_open",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="test",
            name="questions",
            field=models.ManyToManyField(
                help_text="список вопросов в этом тесте",
                related_name="test",
                related_query_name="test",
                to="user_tests.question",
                verbose_name="вопросы",
            ),
        ),
    ]
